null
apache/iotdb pull request #10939
Opened 2023-08-23 07:01 UTC by shuolinl

## Description

### Content1 ...

### Content2 ...

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

##### Key changed/added classes (or packages if there are too many classes) in this PR

2023-08-28 13:33 UTC, JackieTien97 requested changes

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PathPrivilege.java
> +    for (Integer pri : privileges) {
```suggestion
    for (int pri : privileges) {
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +  public static final int sysPriSize = 10;
```suggestion
  public static final int SYS_PRI_SIZE = 10;
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +  public static final int sysPriSize = 10;
Can we directly use Enum to init this field? Because in future, other  people add a new auth, he may forget to change here.

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PathPrivilege.java
> +  private static final Integer priCap = 4;
Can we directly use Enum to init this field? Because in future, other  people add a new auth, he may forget to change here

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +    for (Integer sysPri : sysPrivilegeSet) {
```suggestion
    for (int sysPri : sysPrivilegeSet) {
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +    for (Integer sysPriGrantOpt : sysPriGrantOpt) {
```suggestion
    for (int sysPriGrantOpt : sysPriGrantOpt) {
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +      if ((privilegeMask & (0b1 << i + 16)) != 0) {
```suggestion
      if ((privilegeMask & (1 << (i + 16))) != 0) {
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +      if ((privilegeMask & (0b1 << i)) != 0) {
```suggestion
      if ((privilegeMask & (1 << i)) != 0) {
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +    }
```suggestion
    sysPrivilegeSet.add(privilegeId);
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +    }
```suggestion
    sysPrivilegeSet.remove(privilegeId);
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +    return sysPrivilegeSet.contains(PrivilegeType.values()[privilegeId]);
```suggestion
    return sysPrivilegeSet.contains(privilegeId);
```

2023-08-28 13:33 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserManager.java
> +    }
you can put this call into snapshot take.

2023-08-30 06:33 UTC, shuolinl commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/BrokerAuthenticator.java
> +      // ???
remove

2023-08-30 07:22 UTC, JackieTien97 requested changes

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/BrokerAuthenticator.java
> +      IAuthorizer authorizer = BasicAuthorizer.getInstance();
That's not right. call `authorityFetcher.checkUser`

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/BrokerAuthenticator.java
> +      IAuthorizer authorizer = BasicAuthorizer.getInstance();
In DataNode, we should never have `BasicAuthorizer`.

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
> +  }
Why put this method here?

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
> +      BasicAuthorizer.getInstance().reset();
we should delete this, because there is no user and role folders in datanode any more.

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
> +      privs |= 0b1 << (sysPriTopos(sysPriGrantOpt) + 16);
```suggestion
      privs |= 1 << (sysPriTopos(sysPriGrantOpt) + 16);
```

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleAccessor.java
> +    SystemFileFactory.INSTANCE.getFile(roleDirPath).delete();
```suggestion
    FileUtils.cleanDirectory(SystemFileFactory.INSTANCE.getFile(roleDirPath));
```

2023-08-30 07:22 UTC, JackieTien97 commented on iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserAccessor.java
> +    SystemFileFactory.INSTANCE.getFile(userDirPath).delete();
```suggestion
    FileUtils.cleanDirectory(SystemFileFactory.INSTANCE.getFile(userDirPath));
```

2023-08-30 09:16 UTC, JackieTien97 approved these changes

2023-08-30 09:16 UTC, merged