Support schema region snapshot parser.
apache/iotdb pull request #12145
Opened 2024-03-08 14:25 UTC by shuolinl

In this pr:
1. Support translating snapshot file to statements, so you can use schema region snapshot parser to construct a same Schema tree in another cluster.
2. Add some UTs.

2024-03-11 03:00 UTC, Cpaulyz requested changes
PTAL

2024-03-11 03:00 UTC, Cpaulyz commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SchemaRegionSnapshotParser.java
> +public class SchemaRegionSnapshotParser {
```suggestion
/**
 * Only one thread can be parsing snapshots at a time.
 */
@NotThreadSafe
public class SchemaRegionSnapshotParser {
```

2024-03-13 14:15 UTC, Cpaulyz approved these changes
LGTM

2024-03-14 01:43 UTC, shuolinl commented
@SteveYurongSu Please take a look at this pr.

2024-03-14 09:06 UTC, SteveYurongSu approved these changes

2024-03-14 09:07 UTC, merged