[IOTDB-6325] Support RegionScan for active metadata queries [BE Part One]
apache/iotdb pull request #12539
Opened 2024-05-16 10:47 UTC by ycycse

2024-05-19 04:15 UTC, JackieTien97 requested changes

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskChunkHandleImpl.java
> +    if ((byte) (this.currentChunkHeader.getChunkType() & 63) == 5) {
don't use the magic number here

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskChunkHandleImpl.java
> +    if ((byte) (this.currentChunkHeader.getChunkType() & 63) == 5) {
```
      if (((byte) (chunkHeader.getChunkType() & 0x3F)) == MetaMarker.ONLY_ONE_PAGE_CHUNK_HEADER) {
        pageHeader = PageHeader.deserializeFrom(chunkDataBuffer, chunkStatistic);
        // when there is only one page in the chunk, the page statistic is the same as the chunk, so
        // we needn't filter the page again
      } else {
        pageHeader = PageHeader.deserializeFrom(chunkDataBuffer, chunkHeader.getDataType());
        // if the current page satisfies
        if (pageCanSkip(pageHeader)) {
          skipCurrentPage(pageHeader);
          continue;
        }
      }
```

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskChunkHandleImpl.java
> +    int timeBufferLength = ReadWriteForEncodingUtils.readUnsignedVarInt(currentPageDataBuffer);
timeBufferLength doesn't equal to `line count * 8` because `timeBufferLength` is an encoded bin stream.

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskChunkHandleImpl.java
> +    int timeBufferLength = ReadWriteForEncodingUtils.readUnsignedVarInt(currentPageDataBuffer);
you can get the time length from page header.

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskChunkHandleImpl.java
> +    return timeArray;
we need to use time decoder to decode the `ByteBuffer`, you can refer to `PageReader.getAllSatisfiedData`.

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskAlignedChunkHandleImpl.java
> +    Long[] timeData = sharedTimeDataBuffer.getPageTime(pageIndex);
```suggestion
    long[] timeData = sharedTimeDataBuffer.getPageTime(pageIndex);
```

2024-05-19 04:15 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/DiskAlignedChunkHandleImpl.java
> +    ArrayList<Long> validTimeList = new ArrayList<>();
use long[] and you can get exact value count in its value page header.

2024-05-20 01:37 UTC, ycycse commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
> +    AlignedTVList alignedTVListCopy = (AlignedTVList) memChunk.getSortedTvListForQuery(schemaList);
We don't have measurement info here.

2024-05-20 01:37 UTC, ycycse commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/ClosedFileScanHandleImpl.java
> +              modification ->
Yes, they are similar. We can store List<TimeRange> to reuse this method.

2024-05-20 02:10 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
> +    IChunkMetadata chunkMetadata =
use UNKNOWN instead and add some comments here.

2024-05-20 02:23 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
> +            ModificationUtils.constructDeletionList(
deviceId + measurement = fullPath, you can use FullPath to construct deletion.

2024-05-20 02:25 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
> +              buildChunkMetaDataForMemoryChunk(
ok

2024-05-20 02:40 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
> +        queryContext.getDeviceModifications(tsFileResource, deviceID);
previous processing is also in DataRegion.query.

2024-05-20 02:40 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
> +        queryContext.getDeviceModifications(tsFileResource, deviceID);
same above

2024-05-22 02:35 UTC, JackieTien97 requested changes

2024-05-22 02:35 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/UnclosedFileScanHandleImpl.java
> +              Integer deleteCursor = 0;
this won't be changed in `ModificationUtils.isPointDeleted` and why you use `IntStream.range(0,timeArray.length).forEach` this way to iterate timeArray?

2024-05-22 02:35 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/UnclosedFileScanHandleImpl.java
> +              IntStream.range(0, timeArray.length)
same as above

2024-05-22 02:35 UTC, JackieTien97 commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/filescan/impl/ClosedFileScanHandleImpl.java
> +                  ((AlignedChunkOffset) chunkOffset).getSharedTimeDataBuffer()));
why don't you put this method into `AbstractChunkOffset`?

2024-05-23 00:34 UTC, JackieTien97 approved these changes

2024-05-23 00:34 UTC, merged