Feature add support for query, nonQuery, and insertTablet interfaces for table models in the REST service
apache/iotdb pull request #14165
Opened 2024-11-21 10:40 UTC by CloudWise-Lukemiao

Feature add support for query, nonQuery, and insertTablet interfaces for table models in the REST service.

2024-11-29 02:29 UTC, CritasWang requested changes

2024-11-29 02:29 UTC, CritasWang commented on iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/table/v1/handler/StatementConstructionHandler.java
> +    /*for (int rowIndex = 0; rowIndex < rowSize; rowIndex++) {
Remove useless code

2024-12-17 08:57 UTC, JackieTien97 approved these changes

2024-12-19 07:52 UTC, CritasWang approved these changes

2024-12-19 09:44 UTC, HTHou commented
Consider adding some example code in example module?

2024-12-23 09:38 UTC, HTHou approved these changes

2024-12-23 09:38 UTC, merged