change mem control lock usage
apache/iotdb pull request #2153
Opened 2020-12-01 03:11 UTC by HTHou

2020-12-02 19:57 UTC, jixuan1989 requested changes
why not add a new error code for write_reject_because_overload?

2020-12-02 19:57 UTC, jixuan1989 commented on server/src/main/java/org/apache/iotdb/db/exception/WriteProcessRejectException.java
> +    super(message, TSStatusCode.WRITE_PROCESS_ERROR.getStatusCode());
add a new code?

2020-12-03 02:16 UTC, HTHou commented on server/src/main/java/org/apache/iotdb/db/exception/WriteProcessRejectException.java
> +    super(message, TSStatusCode.WRITE_PROCESS_ERROR.getStatusCode());
Good Idea!

2020-12-04 15:02 UTC, qiaojialin approved these changes

2020-12-05 12:10 UTC, jixuan1989 approved these changes

2020-12-05 12:11 UTC, merged

2020-12-05 12:12 UTC, jixuan1989 commented
Is this related to some known bug? If so, we need to cherry-pick to rel/0.11, otherwise  please delete `mem_control_op` branch