调整Method not supported为具体提示
apache/iotdb pull request #2444
Opened 2021-01-07 09:36 UTC by CloudWise-Lukemiao

## Description

### Content1 ...
### Content2 ...
### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

##### Key changed/added classes (or packages if there are too many classes) in this PR

2021-01-08 05:11 UTC, kr11 commented
Sorry for the misoperation.

2021-01-08 06:30 UTC, jixuan1989 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +   // throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
can we use timstamp (long)?

2021-01-08 06:30 UTC, jixuan1989 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +	  ZonedDateTime zonedDateTime=null;
can we use timstamp (long)?

2021-01-08 06:30 UTC, jixuan1989 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +   // throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
can we use timstamp (long)?

2021-01-08 06:30 UTC, jixuan1989 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +    //throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
better to implement it

2021-01-08 06:30 UTC, jixuan1989 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +    //throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
better to implement it

2021-01-08 06:30 UTC, jixuan1989 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +    //throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
for `Binary` type.

2021-01-08 08:41 UTC, kr11 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
>    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
The method `setArray()` is quite similar to other changed methods, why not let `setArray()` throw `PARAMETER_SUPPORTED` too?

2021-01-08 08:44 UTC, kr11 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +   // throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
Remove commented-out codes

2021-01-08 08:59 UTC, kr11 requested changes
Good jobs but some changes are required.

2021-01-08 08:59 UTC, kr11 commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
> +   // throw new SQLException(METHOD_NOT_SUPPORTED_STRING);
Use `2 spaces` instead of `TAB` as indent characters.
Consider importing the code format  `$IoTDB_HOME/java-google-style.xml` into IDE.

2021-03-01 08:03 UTC, HTHou commented
Hi, to resolve the test failed issue, you may need to apply spotless again...

2021-06-23 10:11 UTC, HTHou commented on jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java
> +import java.sql.*;
We don't suggest to use * here.

2021-06-23 10:11 UTC, HTHou commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
> +import java.util.*;
Same as above.

2021-06-23 10:11 UTC, HTHou commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
>    public IoTDBConnection() {
There is a method `getCatalog()` in this class. I think we can change the return value to the String `IOTDB`.

2021-06-24 01:34 UTC, HTHou commented on thrift/src/main/thrift/rpc.thrift
> +  10:bool isReadOnly;
Don't forget to update the rpc-changelist.md.

2021-06-24 07:30 UTC, HTHou commented on jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
>    }
In IoTDB, we have a `Binary` class that contains a byte array. Can we use it to implement this method?

2021-08-05 14:14 UTC, CloudWise-Lukemiao commented
jdbc add IoTDBJDBCDataSet

2021-08-08 07:52 UTC, qiaojialin approved these changes

2021-08-08 07:57 UTC, HTHou approved these changes

2021-08-08 07:58 UTC, merged