[IOTDB-1214] Add Flink-IoTDB documents
apache/iotdb pull request #2813
Opened 2021-03-11 09:12 UTC by Sunny-Island

Add Flink IoTDB documents to website and docs. The documents include English and Chinese version

2021-03-11 09:17 UTC, SteveYurongSu requested changes

2021-03-11 09:17 UTC, SteveYurongSu commented on docs/UserGuide/Ecosystem Integration/Flink-IoTDB.md
> +The example is to show how to send data to a IoTDB server from a Flink job.
Please put the link of the example on the document :D

2021-03-11 09:17 UTC, SteveYurongSu commented
Good job. Welcome to the IoTDB community!

2021-03-11 09:26 UTC, SteveYurongSu commented
The right doc link: https://github.com/apache/iotdb/tree/master/flink-iotdb-connector

And don't forget the doc of flink-tsfile-connector. :D

2021-03-15 07:01 UTC, jixuan1989 requested changes
see comments

2021-03-15 07:01 UTC, jixuan1989 commented on docs/zh/UserGuide/Ecosystem Integration/Flink IoTDB.md
> +* 运行 `org.apache.iotdb.flink.FlinkTsFileBatchSource.java` 在本地集群上创建一个 Tsfile 并通过一个 Flink Dataset job 读取它。
这些和TsFile相关的似乎不需要在这文档里。

2021-03-16 07:25 UTC, Sunny-Island commented on docs/UserGuide/Ecosystem Integration/Flink IoTDB.md
> +The example is to show how to send data to a IoTDB server from a Flink job.
got it

2021-03-16 07:28 UTC, Sunny-Island commented on docs/UserGuide/Ecosystem Integration/Flink IoTDB.md
> +## Function
New doc is available. This change may not be necessary.

2021-03-22 14:46 UTC, jixuan1989 commented
@Sunny-Island  I modified a few codes.

2021-03-23 03:08 UTC, Sunny-Island commented
Look good to me !

2021-03-23 04:59 UTC, merged

2021-03-24 00:55 UTC, jixuan1989 commented
:( There is an error...
see https://github.com/apache/iotdb/pull/2893