fix some config inconsistent
apache/iotdb pull request #3082
Opened 2021-04-27 12:33 UTC by mychaow

## Description

### Content1 ...

### Content2 ...

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

##### Key changed/added classes (or packages if there are too many classes) in this PR

2021-04-28 01:36 UTC, neuyilan approved these changes
LGTM

2021-04-28 02:53 UTC, wangchao316 approved these changes
LGTM

2021-04-29 01:04 UTC, neuyilan requested changes

2021-04-29 01:04 UTC, neuyilan commented on cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java
> +  private int catchUpTimeoutMS = (int) TimeUnit.SECONDS.toMillis(300);
The  `catch_up_timeout_ms` in iotdb-cluster.properties is 60000, should be change together.
`catch_up_timeout_ms=300000`

2021-04-29 03:13 UTC, neuyilan approved these changes
LGTM

2021-04-29 03:13 UTC, merged