[IOTDB-1496] Timed flush memtable
apache/iotdb pull request #3610
Opened 2021-07-22 09:01 UTC by HeimingZ

Because some memtables are accumulated slowly, so add memtable_flush_interval to flush inactive memtables.

2021-07-24 08:29 UTC, wangchao316 reviewed
Good Job.
There are some problems. If some caches are in use and we just get cleaned up, it's not going to affect its performance.

2021-07-27 01:30 UTC, HeimingZ commented
> Good Job.
> There are some problems. If some caches are in use and we just get cleaned up, it's not going to affect its performance.

1. Users can use unseq_memtable_flush_interval param to specify the alive time of memtables according to their use cases.
2. Change the timed flush level from all memtables to unsequence memtables because zombie memtables often oocurs in unsequence tsfiles.
3. Add enable_timed_flush_unseq_memtable param, so users can decide whether to enable this function.

2021-07-27 08:30 UTC, qiaojialin requested changes

2021-07-27 08:30 UTC, qiaojialin commented on server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
> +    long timestampBaseline = System.currentTimeMillis() - config.getUnseqMemtableFlushInterval();
put into writeLock

2021-07-27 08:38 UTC, HeimingZ commented on server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
> +    long timestampBaseline = System.currentTimeMillis() - config.getUnseqMemtableFlushInterval();
fixed

2021-07-27 09:57 UTC, qiaojialin approved these changes

2021-07-27 09:57 UTC, merged