[IOTDB-1562]incorrect exception processing in insertXXX() API
apache/iotdb pull request #3758
Opened 2021-08-16 15:58 UTC by ShuanglinWu

catch IOTDBException to fix issue_1562

2021-08-17 01:43 UTC, wangchao316 requested changes
Good Job.Thanks for your contribution.
I have a little question, you need add some IT.

2021-08-17 02:31 UTC, cigarl commented
In fact, I think the exception here only throws an `IllegalPathException` on `new PartialPath()`
So we just need to update the current handling of the corresponding exception catch.
In my view，perhaps we should use more specific exception types when handling exceptions ,what do you think？

2021-08-17 03:03 UTC, ShuanglinWu commented
Thanks for reminding, I will add some IT tonight.
------------------------------------------------------------------
发件人：wangchao316 ***@***.***>
发送时间：2021年8月17日(星期二) 09:43
收件人：apache/iotdb ***@***.***>
抄　送：ShuanglinWu ***@***.***>; Author ***@***.***>
主　题：Re: [apache/iotdb] [IOTDB-1562]incorrect exception processing in insertXXX() API (#3758)

@wangchao316 requested changes on this pull request.
Good Job.Thanks for your contribution.
 I have a little question, you need add some IT.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-17 03:11 UTC, ShuanglinWu commented
I think now it's just IllegalPathException, but maybe there will throws an MisMatchDataTypeException or an PathNOtExistException.
        It seems to me that we don't need to catch each exception, but we should get the error message and error code and return them to the client.
------------------------------------------------------------------
发件人：lisijia ***@***.***>
发送时间：2021年8月17日(星期二) 10:31
收件人：apache/iotdb ***@***.***>
抄　送：ShuanglinWu ***@***.***>; Author ***@***.***>
主　题：Re: [apache/iotdb] [IOTDB-1562]incorrect exception processing in insertXXX() API (#3758)

In fact, I think the exception here only throws an IllegalPathException on new PartialPath()
 So we just need to update the current handling of the corresponding exception catch.
 In my view，perhaps we should use more specific exception types when handling exceptions ,what do you think？
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-30 12:56 UTC, qiaojialin commented on server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
> +  private TSStatus onIOTDBException(Exception e, String operation, int errorCode) {
```suggestion
  private TSStatus onIoTDBException(Exception e, String operation, int errorCode) {
```

2021-08-30 12:56 UTC, qiaojialin commented on server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
> +            .put(i, onIOTDBException(e, "inserting records", e.getErrorCode()));
Better to move all these "inserting records" to a IoTDBConstant or a n Enum class

2021-08-30 15:27 UTC, qiaojialin approved these changes

2021-09-03 12:22 UTC, qiaojialin commented on session/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
> +                      "[%s] Exception occurred: %s failed. %s is not a legal path",
extract a constant string in this class

2021-09-04 06:06 UTC, qiaojialin approved these changes

2021-09-05 10:30 UTC, wangchao316 approved these changes
LGTM

2021-09-05 13:05 UTC, HTHou approved these changes

2021-09-05 13:06 UTC, merged