[IOTDB-2272] implement customized sync process: receiver
apache/iotdb pull request #4786
Opened 2022-01-12 07:45 UTC by Cpaulyz

This pr mainly contains three modules of sync receiver:
* **SQL parser**
  * `START PIPESERVER`
  * `STOP PIPESERVER`
  * `SHOW PIPESERVER <pipeName>?`
* **ReceiverService** (aka PipeServer)
  * in `ReceiverService`
  * It a IService and entry for processing requests about the receiving data.
* **ReceiverManager**
  * in package manager and recover
  * Responsible for maintaining status information and writing to logs. It provides the ability to recover when restart IOTDB.
  * There are some UT in `ReceiverManagerTest` and `ReceiverLogAnalyzerTest`

design document: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=195730287

2022-01-21 13:18 UTC, yschengzi requested changes
please fix them

2022-01-22 06:49 UTC, Cpaulyz commented on server/src/main/java/org/apache/iotdb/db/newsync/receiver/manager/ReceiverManager.java
> +  private Map<String, Map<String, PipeInfo>> pipeInfoMap;
Yes, maybe there are many pipes with the same pipeNames. For thses two choice, `Map<remoteIP, List<pipeName, pipeInfo>>` have the advantage over storage cost. 

However, considering sql `SHOW PIPESERVER [pipeName] `, we need to provide function `getPipeInfos(String pipeName)`. The time complexity of the origin choice is O(1) while another is O(n).

2022-01-25 03:17 UTC, yschengzi approved these changes

2022-01-25 03:17 UTC, yschengzi approved these changes

2022-01-25 03:19 UTC, merged