[IOTDB-2469]Update code of pulsar example with sessionPool api
apache/iotdb pull request #4957
Opened 2022-01-21 16:25 UTC by Alibaba-HZY

2022-01-22 00:55 UTC, wangchao316 requested changes

2022-01-22 00:55 UTC, wangchao316 commented on example/pulsar/src/main/java/org/apache/iotdb/pulsar/PulsarConsumerThread.java
> +    ;
this ";" ？

2022-01-22 12:44 UTC, jack870131 approved these changes

2022-01-24 08:50 UTC, wangchao316 approved these changes
LGTM

2022-01-24 08:51 UTC, merged