Avoid flush stream in getPosition() to improve flush performance
apache/iotdb pull request #4963
Opened 2022-01-24 03:38 UTC by chengjianyun

current getPosition() will trigger flush which cause the bufferStream doesn't take effect as getPosition is triggered in too many times.

Fix the issue to help improve flush performance.

2022-01-24 08:54 UTC, qiaojialin approved these changes

2022-01-24 09:30 UTC, JackieTien97 requested changes
It seems that `synchronized` is unnecessary. Will the `LocalTsFileOutput` be used in multi-thread case?

2022-01-25 03:11 UTC, chengjianyun commented
> It seems that `synchronized` is unnecessary. Will the `LocalTsFileOutput` be used in multi-thread case?

I think the class is a stream wrapper and a low-level class. It's better to make it multi-thread safe just as the other stream implementations do.

2022-01-26 03:19 UTC, qiaojialin commented
> > It seems that `synchronized` is unnecessary. Will the `LocalTsFileOutput` be used in multi-thread case?
> 
> The class is a low-level stream wrapper. It's better to make it multi-thread safe just as the other stream implementations do. How to you think?

+1

2022-01-27 01:14 UTC, JackieTien97 approved these changes

2022-01-28 01:20 UTC, merged