Apply string intern for device String
apache/iotdb pull request #4964
Opened 2022-01-24 03:52 UTC by chengjianyun

The implementation of cacheString pool has the memory leak risk. We can use string intern instead of do it by ourself.

2022-01-24 08:55 UTC, wangchao316 requested changes

2022-01-24 08:55 UTC, wangchao316 commented on server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
> +import java.util.*;
Good
does not import *

2022-01-24 08:55 UTC, wangchao316 commented on server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
> +import org.apache.iotdb.db.exception.*;
the same as above...

2022-01-25 03:03 UTC, chengjianyun commented on server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
> +import java.util.*;
Done.

2022-01-25 03:03 UTC, chengjianyun commented on server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
> +import org.apache.iotdb.db.exception.*;
Done.

2022-01-25 03:15 UTC, wangchao316 approved these changes
LGTM

2022-01-26 07:58 UTC, HTHou commented
Hi, is there any detailed reason about the memory leak risk?

2022-01-26 08:07 UTC, chengjianyun commented
> Hi, is there any detailed reason about the memory leak risk?

`cachedDevicePool` never remove its key which is not reasonable. For example, if we delete some storage groups or timeseries, some string would be never used but they are always kept in `cachedDevicePool` which cause memory leak.

For string intern, JVM takes care of remove the useless string objects.

2022-01-27 06:22 UTC, Alima777 commented
> For example, if we delete some storage groups or timeseries, some string would be never used but they are always kept in `cachedDevicePool` which cause memory leak.

Hi, it's true that we can't handle the useless string if we delete some devices. But the intern() method is not that fast[1][2] since the purpose of it is to save memory. By comparison, `concurrentHashMap` has a good performance. 
I believe that the situation about deleting timeseries or storage group is relatively few. And we use `deviceIndexMap` when we initialize TsFileResource, when restarting or ingesting data, the performance seems more important. Maybe we need to make a balance here. Or we can delete useless string from `cachedStringPool` manually when time series is deleted.
What do you think?


[1] https://stackoverflow.com/questions/56203500/java-string-intern-use-hashtable-instead-of-concurrenthashmap
[2] https://www.fatalerrors.org/a/jvm-series-string.intern-performance-of.html

2022-01-27 08:44 UTC, chengjianyun commented
> > For example, if we delete some storage groups or timeseries, some string would be never used but they are always kept in `cachedDevicePool` which cause memory leak.
> 
> Hi, it's true that we can't handle the useless string now if we delete some devices. But the `intern()` method is not that fast[1][2] since the purpose of it is to save memory. By comparison, `concurrentHashMap` has a good performance. I believe that the situation about deleting timeseries or storage group is relatively few. And we use `deviceIndexMap` when we initialize TsFileResource, when restarting or ingesting data, the performance seems more important. Maybe we need to make a balance here. Or we can delete useless string from `cachedStringPool` manually when time series is deleted instead of just using `intern()`. What do you think?
> 
> [1] https://stackoverflow.com/questions/56203500/java-string-intern-use-hashtable-instead-of-concurrenthashmap [2] https://www.fatalerrors.org/a/jvm-series-string.intern-performance-of.html

@Alima777, about performance of  `String.intern()`, you can also refer  [this blog](http://java-performance.info/string-intern-in-java-6-7-8/). I have verified the conclusion and got similar result on JDK8. So, it's better to set the `-XX:StringTableSize` when go bad perfromance on `intern()` method. And the performance improved much since JDK11 event without  `-XX:StringTableSize` parameter.

BTW, memory leak is intolerable in any cases especially in a database server system.

2022-01-27 09:56 UTC, Alima777 commented
> BTW, memory leak is intolerable in any cases especially in a database server system in my opinion.

Hi, I understand your concerns. So what I said is `we can delete useless string from cachedStringPool manually when time series is deleted` to avoid memory leak. I didn't check the conclusion about memory footprint using `WeakHashMap`, maybe it stores more things than normal HashMap?

2022-01-27 11:09 UTC, chengjianyun commented
> we can delete useless string from cachedStringPool manually when time series is deleted

As far as I know, we can do this by count references to each object like older verion JVM GC does. If we do like this, why don't let JVM help recycle the memory usage by use `WeakHashMap`? Or do you have other ideas?

> `WeakHashMap` is 4~5 times than`intern()`, is `concurrentHashMap` still the same?

The HashMap or ConcurrentHashMap implemented CachePool is wrong without explicit clear, so I didn't verify with them.

2022-01-27 12:23 UTC, Alima777 commented
> As far as I know, we can do this by count references to each object like older verion JVM GC does.

Hi, you should know we only use this `cachedStringPool` in limited situation. It's only used in TsFileResource. So count references maybe not needed, we just add it when initialize, and remove it when delete timeseries.

2022-01-28 06:44 UTC, chengjianyun commented
> So count references maybe not needed, we just add it when initialize, and remove it when delete timeseries.

I don't think this way would work. As the strings from `CacheStringPool` are passed to different instances, you must know all of the references of a key are released then the `CacheStringPool` could remove the key. Otherwise, you would hold different instances for same string which will lose the meaning of `CacheStringPool`. 

And for the class, it designs to provide ability like string intern, but has implementation defects. You can't restrict it only used to hold device or measurement path unless you name it something like `DevicePathPool` or `MeasurementPathPool` instead of `CacheStringPool`.

The two ways I can figure out are either use `WeakHashMap<String, WeakRefernce<String>>` instead of `ConcurrentHashMap` or  `String.intern()`. I prefer the later one in the PR.

2022-01-28 08:38 UTC, qiaojialin commented
> memory leak is intolerable in any cases especially in a database server system in my opinion.

+1

2022-01-28 08:58 UTC, JackieTien97 approved these changes

2022-01-28 09:00 UTC, qiaojialin approved these changes

2022-01-28 09:00 UTC, merged