[IOTDB-2747] Start data node
apache/iotdb pull request #5330
Opened 2022-03-23 14:09 UTC by MrQuansy

2022-03-24 05:37 UTC, OneSizeFitsQuorum reviewed
PTAL. Many class names and class dependencies need to be discussed in detail with MPP query module

2022-03-24 05:37 UTC, OneSizeFitsQuorum commented on node-commons/src/main/java/org/apache/iotdb/commons/utils/CommonUtils.java
> +      logger.warn("Bad node url: {}", nodeUrl);
return null?

2022-03-24 05:37 UTC, OneSizeFitsQuorum commented on server/pom.xml
> +            <version>0.14.0-SNAPSHOT</version>
${project.version}

2022-03-24 05:37 UTC, OneSizeFitsQuorum commented on server/pom.xml
> +            <version>0.14.0-SNAPSHOT</version>
${project.version}

2022-03-24 05:37 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
> +  private long joinClusterTimeOutMs = TimeUnit.SECONDS.toMillis(5);
Maybe large? such as 1 minute?

2022-03-24 05:37 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
> +        replaceHostnameWithIP();
Maybe we do not need this anymore if we can use FQDN to identify our nodes

2022-03-24 08:50 UTC, JackieTien97 requested changes
Better to renane  all `DataNodeInternalServiceXXX` to `DataNodeManagementService`, internal servcei will be used to refer to rpc service between data nodes.

2022-03-24 10:44 UTC, chengjianyun commented on server/src/assembly/resources/sbin/start-node.bat
> +@REM
rename the file to start-data-node.bat?

2022-03-24 12:04 UTC, MrQuansy commented on server/src/assembly/resources/sbin/start-node.bat
> +@REM
ok

2022-03-24 13:40 UTC, HTHou approved these changes

2022-03-25 01:40 UTC, JackieTien97 approved these changes

2022-03-25 01:47 UTC, JackieTien97 requested changes
Don't change the previous TsServiceImpl

2022-03-25 02:54 UTC, JackieTien97 approved these changes

2022-03-25 02:55 UTC, merged