[IOTDB-2899] Feature/set storage group
apache/iotdb pull request #5510
Opened 2022-04-13 09:49 UTC by SpriCoder

See more details: https://issues.apache.org/jira/browse/IOTDB-2899

2022-04-13 11:23 UTC, JackieTien97 requested changes

2022-04-13 11:23 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/sql/parser/ASTVisitor.java
> +    return super.visitSetStorageGroup(ctx);
You should construct SetStorageGroupStatement here by yourselft. You can refer the implementation in `visitSetStorageGroup` of `IoTDBSqlVisitor`.

2022-04-13 11:23 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/Analyzer.java
> +
You don't need to do analyze here, Config related Statement won't reach here.

2022-04-13 11:23 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/IConfigTask.java
> +  ListenableFuture<Void> execute() throws IoTDBConnectionException, MetadataException;
You don' have to throw these checked execption here.

2022-04-13 11:23 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +    return Futures.immediateVoidFuture();
```
    SettableFuture<Void> future = SettableFuture.create();
    try {
      // do something you want to do
      future.set(null);
    } catch (IoTDBConnectionException | BadNodeUrlException e) {
      // catch checked exception here.
      future.setException(e);
    }
    return future;
```

2022-04-13 11:23 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +    return Futures.immediateVoidFuture();
Avoid throw checked exception out of this scope.

2022-04-13 12:19 UTC, SpriCoder commented
Thanks for you review. all problem are already fixed. @JackieTien97 PTAL!

2022-04-14 02:27 UTC, JackieTien97 requested changes

2022-04-14 02:27 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +  private Statement statement;
```suggestion
  private final SetStorageGroupStatement statement;
```

2022-04-14 02:27 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +  public SetStorageGroupTask(Statement statement) {
```suggestion
  public SetStorageGroupTask(SetStorageGroupStatement statement) {
```

2022-04-14 02:27 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +    }
Don't need to do this if judgement here.

2022-04-14 02:27 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +    }
```suggestion
```

2022-04-14 02:27 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +        future.setException(new MetadataException("Failed to connect to config node."));
```suggestion
        LOGGER.error("Failed to execute set storage group {} in config node, status is {}.", statement.getStorageGroupPath(), tsStatus);
        future.setException(new StatementExecutionException(tsStatus));
```

2022-04-14 02:27 UTC, JackieTien97 commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
> +      }
```suggestion
      } else {
        future.set(null);
      }
```

2022-04-14 06:06 UTC, JackieTien97 approved these changes

2022-04-14 06:06 UTC, merged