[IOTDB-3556] Maintain onlineConfigNodes by LoadManager
apache/iotdb pull request #6532
Opened 2022-06-30 04:12 UTC by RYH61

2022-06-30 06:49 UTC, CRZbulabula requested changes
PTAL~

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
> +    if (!configManager.getLoadManager().getOnlineConfigNodes().contains(configNodeLocation)) {
getRegisteredConfigNodes

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
> +    configNodeLocations.addAll(configManager.getLoadManager().getOnlineConfigNodes());
getRegisteredConfigNodes

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
>        // TODO: Check ConfigNode status, ensure the returned ConfigNode isn't removed
This typo can be removed now

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +  private List<TConfigNodeLocation> onlineConfigNodes;
We shouldn't add another field in LoadManager

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +  private List<TConfigNodeLocation> onlineConfigNodes;
We shouldn't add another field in LoadManager

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +      pingOnlineConfigNodes(getNodeManager().getRegisteredDataNodes());
This interface should be renamed to pingRegisteredConfigNodes

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +    return onlineConfigNodes;
New List<TConfigNodeLocation> to store the result, thus we don't have to maintain the onlineConfigNodes field in LoadManager

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
> +    dataSet.setConfigNodeList(getLoadManager().getOnlineConfigNodes());
getRegisteredConfigNodes

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
> +    resp.setConfigNodeList(getLoadManager().getOnlineConfigNodes());
getRegisteredConfigNodes

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
> +            .contains(removeConfigNodePlan.getConfigNodeLocation())) {
getRegisteredConfigNodes and modify the typo here

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
> +        List<TConfigNodeLocation> onlineConfigNodes = getLoadManager().getOnlineConfigNodes();
getRegisteredConfigNode

2022-06-30 06:49 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
> +      dataSet.setConfigNodeList(loadManager.getOnlineConfigNodes());
getRegisteredConfigNodes

2022-06-30 09:15 UTC, RYH61 commented on confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
> +    configNodeLocations.addAll(configManager.getLoadManager().getOnlineConfigNodes());
fixed~

2022-06-30 09:57 UTC, CRZbulabula reviewed
PTAL~

2022-06-30 09:57 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
>          // Check ConfigNodes number
Fix typo

2022-06-30 09:57 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
>          // Check whether the onlineConfigNodes contain the ConfigNode to be removed.
Fix typo

2022-06-30 09:57 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +      pingOnlineConfigNodes(getNodeManager().getRegisteredConfigNodes());
pingRegisteredConfigNodes

2022-06-30 10:08 UTC, CRZbulabula approved these changes
LGTM

2022-06-30 15:17 UTC, qiaojialin commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
>        // Send heartbeat requests to all the online ConfigNodes
```suggestion
      // Send heartbeat requests to all the registered ConfigNodes
```

2022-06-30 15:17 UTC, qiaojialin commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +  private void pingRegisteredConfigNodes(List<TConfigNodeLocation> onlineConfigNodes) {
```suggestion
  private void pingRegisteredConfigNodes(List<TConfigNodeLocation> registeredConfigNodes) {
```

2022-06-30 15:17 UTC, qiaojialin commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
>     * @param onlineConfigNodes ConfigNodes that currently online
```suggestion
   * @param registeredConfigNodes ConfigNodes that registered in cluster
```

2022-06-30 16:25 UTC, RYH61 commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
>     * @param onlineConfigNodes ConfigNodes that currently online
fixed~

2022-06-30 16:26 UTC, RYH61 commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +  private void pingRegisteredConfigNodes(List<TConfigNodeLocation> onlineConfigNodes) {
fixed~

2022-06-30 16:26 UTC, RYH61 commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
>        // Send heartbeat requests to all the online ConfigNodes
fixed~

2022-07-01 01:51 UTC, qiaojialin approved these changes

2022-07-01 01:51 UTC, merged