[IOTDB-3528] Filter DataNode which may not be ready in ConfigNode
apache/iotdb pull request #6539
Opened 2022-06-30 12:10 UTC by imquanke

## [IOTDB-3528] Filter DataNode which may not be ready in ConfigNode

### If data structure in DataNode A has not been initialized，but it has registered itself into ConfigNode，and meanwhile its Internal RPC Service has been set up. At this time if someone send request through another DataNode B，then the request is dispatched to DataNode A，it will cause NPE.<br>So we should filter dataNodes which may not be ready in ConfigNode

2022-07-01 02:11 UTC, CRZbulabula requested changes
PTAL~

2022-07-01 02:11 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
> -      ConsensusWriteResponse resp = getConsensusManager().write(req);
We can't delete this consensus write here, otherwise the ConfigNode-follower's nextNodeId in NodeInfo won't be updated

2022-07-01 02:11 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/ActivateDataNodePlan.java
> +  }
Add serialize and deserialize test in ConfigPhysicalPlanSerDeTest

2022-07-01 02:11 UTC, CRZbulabula commented on confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessorTest.java
>      dataNodeLocation.setSchemaRegionConsensusEndPoint(new TEndPoint("0.0.0.0", 50011));
Also test re-active here~

2022-07-01 08:56 UTC, CRZbulabula approved these changes
LGTM~

2022-07-02 01:58 UTC, qiaojialin approved these changes

2022-07-02 01:58 UTC, merged