[IOTDB-3955] Improved node information metrics to push more detailed node information, online and offline total and survival information of each node
apache/iotdb pull request #6801
Opened 2022-07-27 07:32 UTC by 23931017wu

## Improved node information metrics to push more detailed node information, online and offline total and survival information of each node

### Metrics are added when the heartbeat service is started and deleted when the heartbeat service is stopped.

### These metrics include the total number of online and unknown nodes, And the survival status of each node.

#### The survival status of the current node is represented by 1:online,0:unkonwn.
data_node{name="EndPoint(127.0.0.1:6671)",status="1:online,0:unkonwn",} 1.0
config_node{name="EndPoint(0.0.0.0:22277)",status="1:online,0:unkonwn",} 1.0
#### The total number of registed nodes is represented by registed.
data_node{name="total",status="registed",} 1.0
config_node{name="total",status="registed",} 1.0
#### The total number of online nodes is represented by online.
data_node{name="total",status="online",} 2.0
config_node{name="total",status="online",} 2.0
#### The total number of unknown nodes is represented by unknown.
data_node{name="total",status="unknown",} 1.0
config_node{name="total",status="unknown",} 1.0

### Test:
#### Start the 3C3D first 
![image](https://user-images.githubusercontent.com/71131924/181187628-bd46bedf-4b82-4c91-994e-98f655b1df67.png)
#### Displayed on the Grafana dashboard
![image](https://user-images.githubusercontent.com/71131924/181187708-a44b51b0-76a6-4018-ba0d-299afff006ff.png)
#### Stop 1 ConfigNode and 1 DataNode
![image](https://user-images.githubusercontent.com/71131924/181188138-0a2e5b75-a7c8-428b-b848-936bd9a03131.png)
#### Displayed on the Grafana dashboard
![image](https://user-images.githubusercontent.com/71131924/181188187-259732de-0334-478d-afe8-964b1301eb9b.png)

##### Key changed/added classes (or packages if there are too many classes) in this PR

2022-07-27 07:46 UTC, mychaow commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +                      "1:online,0:unkonwn")
status should be online or unknown? no need to public 1 or 0

2022-07-27 07:47 UTC, mychaow commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
> +              "registed");
registered

2022-07-27 07:50 UTC, mychaow commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +    for (TDataNodeConfiguration dataNodeInfo : allDataNodes) {
I think the confignode/datanode ip metric is too many. 
And I do not think the online time is important.  
In current implement, if I delete some datanode, but the metric exists.

2022-07-27 10:27 UTC, mychaow approved these changes
LGTM

2022-07-29 05:09 UTC, SpriCoder requested changes
PTAL~
Besides, I have two other problems:
1. Please update metric doc at the same time: docs/UserGuide/Maintenance-Tools/Metric-Tool.md and docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
2. Maybe you can update the dashboard at the same time.

2022-07-29 05:09 UTC, SpriCoder commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +    LOGGER.info("Remove loadManager metrics");
This log is useless.

2022-07-29 05:09 UTC, SpriCoder commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
> +  }
I think the value of tag can be the name of NodeStatus enums to remove hard code.

2022-07-29 05:09 UTC, SpriCoder commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
> +              "registered");
I think the value of tag can be the name of NodeStatus enums to remove hard code.

2022-07-29 05:09 UTC, SpriCoder commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
> +              "registered");
I think the value of tag can be the name of NodeStatus enums to remove hard code.

2022-08-01 01:53 UTC, neuyilan approved these changes
LGTM

2022-08-02 05:14 UTC, merged