[IOTDB-4202]delete from not exist timeseries return success
apache/iotdb pull request #7081
Opened 2022-08-22 04:52 UTC by yifuzhou

## Description

### Content1 ...

### Content2 ...

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

##### Key changed/added classes (or packages if there are too many classes) in this PR

2022-08-22 06:09 UTC, wangchao316 approved these changes
LGTM

2022-08-22 07:24 UTC, MarcosZyk approved these changes

2022-08-22 07:33 UTC, wangchao316 requested changes
需要注意的是，当删除的路径不存在时，IoTDB 不会提示路径不存在，而是显示执行成功，因为 SQL 是一种声明式的编程方式，除非是语法错误、权限不足等，否则都不认为是错误，如下所示。

Need to discuss

2022-08-22 12:48 UTC, yifuzhou commented
@qiaojialin can you review it? Should we let all delete sqls return successfully or give an error code if paths do not exist?

2022-08-30 06:56 UTC, qiaojialin commented
Hi, as no user raise this issue, we'd better keep the notation consistent with 0.13 version, just return success is fine.

2022-08-30 07:14 UTC, qiaojialin requested changes
Hi, there is no detailed requirements, won't do now.

2022-08-31 07:08 UTC, wangchao316 approved these changes
LGTM

2022-08-31 13:06 UTC, qiaojialin approved these changes

2022-08-31 13:06 UTC, merged