[IOTDB-4399] Control chunk size in memtable
apache/iotdb pull request #7320
Opened 2022-09-15 00:56 UTC by MrQuansy

2022-09-16 03:12 UTC, qiaojialin requested changes

2022-09-16 03:12 UTC, qiaojialin commented on server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
> +    rawSize += getBinarySize(value);
This should already be estimated before write, store the memory in Binary and use here

2022-09-16 03:12 UTC, qiaojialin commented on server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
> +    return false;
What are you coding? You add a reachMaxChunkSizeFlag but never use it.
Add UTs

2022-09-21 06:46 UTC, HTHou commented on server/src/assembly/resources/conf/iotdb-datanode.properties
> +# Datatype: int
long?

2022-09-22 01:28 UTC, HTHou commented on server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
> +  protected long[] valueChunkRawSize;
Add javadoc?

2022-09-22 05:37 UTC, HTHou approved these changes

2022-09-22 05:37 UTC, merged