Added test api for partitions
apache/iotdb pull request #7497
Opened 2022-09-30 08:33 UTC by Caideyipi

## Added test api for partitions at confignodes
related document：https://apache-iotdb.feishu.cn/docx/doxcnA4xpA6vrmKssH2GgbeHFhh
The inputs and outputs are defined there.

### getRouting
Query a timePartition's corresponding dataRegionIds

### getTimeSlotList
Query a seriesSlot's timeSlots between startTime and endTime

### getSeriesSlotList
Query a storageGroup's seriesSlots, using TConsensusGroupType to detect the type of returned seriesSlots.

### Haven't been tested!
Don't merge it until someone tests the functions.

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

##### Key changed/added classes (or packages if there are too many classes) in this PR

2022-10-05 01:17 UTC, CRZbulabula requested changes
PTAL~

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
> +  public TGetRoutingResp getRouting(TGetRoutingReq req) {
Define this interface in IManager

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
> +  public TGetTimeSlotListResp getTimeSlotList(TGetTimeSlotListReq req) {
Define this interface in IManager

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
> +  public TGetSeriesSlotListResp getSeriesSlotList(TGetSeriesSlotListReq req) {
Define this interface in IManager

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
> +  }
Better use ConsensusManager.read() interface to implement these interfaces~

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
> +    if (!storageGroupPartitionTables.containsKey(storageGroup)) {
```suggestion
    if (!isStorageGroupExisted(storageGroup)) {
```

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
> +    if (!storageGroupPartitionTables.containsKey(storageGroup)) {
```suggestion
    if (!isStorageGroupExisted(storageGroup)) {
```

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
> +    if (!storageGroupPartitionTables.containsKey(storageGroup)) {
```suggestion
    if (!isStorageGroupExisted(storageGroup)) {
```

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java
> -
Please keep this interface since it might be invoked later~

2022-10-05 01:17 UTC, CRZbulabula commented on confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java
> +            .collect(Collectors.toList());
Duplicate values need to be cleaned up in this return value

2022-10-05 01:19 UTC, CRZbulabula commented
We also need to add the corresponding SQL for these interfaces

2022-10-07 05:29 UTC, Beyyes approved these changes

2022-10-07 05:30 UTC, Beyyes reviewed
Please check the CI

2022-10-07 10:17 UTC, Caideyipi commented on node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
> -   * @throws IllegalPathException
Because idea suggests that this line may be redundant

2022-10-07 10:17 UTC, Caideyipi commented on confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
> +  @TestOnly
Will apply that~

2022-10-08 07:27 UTC, Beyyes approved these changes
LGTM

2022-10-10 02:47 UTC, Caideyipi commented
> sponding S

Start doing this~

2022-10-10 05:50 UTC, merged