[IOTDB-5462] Optimize the memory estimation of ExchangeOperator in the pipeline
apache/iotdb pull request #8970
Opened 2023-02-03 01:21 UTC by liuminghui233

2023-02-07 03:43 UTC, JackieTien97 requested changes
same as `dealWithConsumeChildrenOneByOneNode`

2023-02-07 03:44 UTC, JackieTien97 requested changes
same as `dealWithConsumeChildrenOneByOneNode` and remember to add a UT about this.

2023-02-07 06:46 UTC, liuminghui233 commented
> same as `dealWithConsumeChildrenOneByOneNode` and remember to add a UT about this.

UT added.
In the `dealWithConsumeChildrenOneByOneNode` method, `ExchangeOperator` is not added, so there is no need to modify it.

2023-02-27 02:21 UTC, Alima777 approved these changes

2023-02-27 09:05 UTC, merged