[IOTDB-5502] Source counters for construct batches in IoTConsensus
apache/iotdb pull request #9023
Opened 2023-02-08 17:03 UTC by BUAAserein

## Description
### Add two counters for construct batches in IoTConsensus. Please see details in [IOTDB-5502](https://issues.apache.org/jira/browse/IOTDB-5502).

2023-02-09 07:09 UTC, neuyilan approved these changes
LGTM

2023-02-09 08:52 UTC, OneSizeFitsQuorum commented on consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/Batch.java
> +      logEntriesNumFromWAL += 1;
logEntriesNumFromWAL++

2023-02-09 08:52 UTC, OneSizeFitsQuorum commented on consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
> +  private final AtomicLong logEntriesFromConsensusRequest = new AtomicLong(0);
FromConsensusRequest -> FromQueue

2023-02-09 09:36 UTC, SpriCoder requested changes
Excellent Work!
Just one problem, Please update the en and zh doc at same time
en: docs/UserGuide/Monitor-Alert/Metric-Tool.md
zh: docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md

2023-02-10 07:08 UTC, BUAAserein commented on consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/Batch.java
> +      logEntriesNumFromWAL += 1;
ok

2023-02-10 07:08 UTC, BUAAserein commented on consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
> +  private final AtomicLong logEntriesFromConsensusRequest = new AtomicLong(0);
ok

2023-02-10 07:08 UTC, BUAAserein commented
> Excellent Work! Just one problem, Please update the en and zh doc at same time en: docs/UserGuide/Monitor-Alert/Metric-Tool.md zh: docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md

2023-02-10 08:05 UTC, OneSizeFitsQuorum approved these changes
LGTM

2023-02-10 18:06 UTC, SpriCoder approved these changes
LGTM~

2023-02-12 04:11 UTC, merged