[IOTDB-5515] Support GROUP BY SERIES in aggregation query
apache/iotdb pull request #9042
Opened 2023-02-10 07:52 UTC by ycycse

UserGuide: https://apache-iotdb.feishu.cn/docx/NgCXdVmPSoTdZsx3TzNcF0J9n6d
Design doc: https://apache-iotdb.feishu.cn/docx/N1Mmd3HWyoDjohxCO9ic6JO2nXc

2023-02-13 01:16 UTC, ycycse commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/SeriesWindowManager.java
> +  }
It will be removed when the PR of COUNT_IF is merged.

2023-02-13 02:15 UTC, ycycse commented on server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/component/GroupBySeriesComponent.java
> +  }
removed.

2023-02-13 13:10 UTC, JackieTien97 requested changes

2023-02-13 16:11 UTC, ycycse commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/SeriesWindow.java
> +  private final SeriesWindowParameter seriesWindowParameter;
done.

2023-02-14 02:07 UTC, ycycse commented on integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupBySeriesIT.java
> +public class IoTDBGroupBySeriesIT {
done.

2023-02-14 02:07 UTC, ycycse commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/SeriesWindow.java
> +  private final SeriesWindowParameter seriesWindowParameter;
done.

2023-02-14 02:07 UTC, ycycse commented on server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
>    public boolean isGroupByVariation() {
done.

2023-02-14 02:08 UTC, ycycse commented on server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/SeriesWindowManager.java
> +  public void initCurWindow(TsBlock tsBlock) {
done.

2023-02-14 06:13 UTC, Wei-hao-Li approved these changes

2023-02-15 01:45 UTC, liuminghui233 approved these changes
LGTM about fe part :-)

2023-02-15 06:39 UTC, JackieTien97 approved these changes

2023-02-15 06:39 UTC, merged