[IOTDB-4837] Refactor Set Schema Template
apache/iotdb pull request #9637
Opened 2023-04-18 02:09 UTC by MarcosZyk

## Description

### Content1 ...

### Content2 ...

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

##### Key changed/added classes (or packages if there are too many classes) in this PR

2023-04-19 07:54 UTC, CRZbulabula approved these changes
LGTM～

2023-04-19 11:16 UTC, Cpaulyz requested changes

2023-04-19 12:38 UTC, MarcosZyk commented on server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
> +                    filterPathPatternTree(patternTree, schemaRegion.getStorageGroupFullPath());
Fixed.

2023-04-19 12:38 UTC, MarcosZyk commented on server/src/main/java/org/apache/iotdb/db/exception/metadata/template/TemplateImcompatibeException.java
> +  }
Removed meaningless check and usage.

2023-04-19 12:53 UTC, MarcosZyk commented on confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/SetTemplateProcedure.java
> +      if (entry.getValue().getCode() != TSStatusCode.SUCCESS_STATUS.getStatusCode()) {
I think it's ok to keep current implementation since we can report precise failure info on specific DataNode.

2023-04-19 12:53 UTC, MarcosZyk commented on confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/SetTemplateProcedure.java
> +      if (entry.getValue().getCode() != TSStatusCode.SUCCESS_STATUS.getStatusCode()) {
I think it's ok to keep current implementation since we can report precise failure info on specific DataNode.

2023-04-19 13:19 UTC, MarcosZyk commented on thrift/src/main/thrift/datanode.thrift
> +  2: optional i64 count
Fixed.

2023-04-19 13:55 UTC, MarcosZyk commented on server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
> +        schemaFetcher.checkTemplateSetAndPreSetInfo(timeseriesPath);
Fixed.

2023-04-20 01:58 UTC, Cpaulyz approved these changes
LGTM

2023-04-20 02:09 UTC, merged