Add file num and size metrics for each level file
apache/iotdb pull request #9953
Opened 2023-05-26 07:24 UTC by THUMarkLau

This PR add metrics for file count and size in each compaction level, which may help us to tune the system online.

2023-05-26 11:34 UTC, THUMarkLau commented
This PR is set to draft until I fix the code smell next week.

2023-05-29 03:59 UTC, SpriCoder requested changes
PTAL~

2023-05-29 03:59 UTC, SpriCoder commented on server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java
> +          .set(count);
Consider avoiding the acquire of gauge from metric service. Instead, we can create a metric set to manage all related metrics, including creation, update and remove, more details: https://github.com/apache/iotdb/pull/9901

2023-05-29 11:02 UTC, SpriCoder requested changes
PTAL~

2023-05-29 11:02 UTC, SpriCoder commented on server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
> +    TS_FILE_METRIC_MANAGER.setMetricService(metricService);
A little bit strange. We use TS_FILE_METRIC_MANAGER to manage metrics and add metric service into TS_FILE_METRIC_MANAGER. From my perspective, I think we can use TS_FILE_METRIC_MANAGER to manage related value, and use Metric Set to manage metric(get value from TS_FILE_METRIC_MANAGER)

2023-05-30 03:37 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java
> +      log.error("Unexpected error occurred when getting tsfile name", e);
use warn?

2023-05-31 04:03 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
> +  public void deleteFile(List<Long> sizeList, boolean seq, int num, List<String> names) {
remove num

2023-05-31 04:03 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
> +  private static final long UPDATE_INTERVAL = 10_000L;
Put that value in a more basic class?

2023-05-31 04:03 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
> +  private List<Long> deleteOldFiles(List<TsFileResource> tsFileResourceList) {
use long[]

2023-05-31 04:03 UTC, OneSizeFitsQuorum commented on server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
> +        List<String> fileNames = new ArrayList<>();
Avoid extended copying of arrays

2023-05-31 06:15 UTC, OneSizeFitsQuorum approved these changes
LGTM

2023-05-31 09:17 UTC, merged